//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompiledRazorTemplates.Dynamic
{
    using System;
    using MWMS;
    using MWMS.Helper;
    using System.Collections.Generic;
    using System.Linq;


    public class fbefcaa : RazorEngine.Templating.TemplateBase<System.Object[]>
    {

#line hidden


        public fbefcaa()
        {
        }

        public override void Execute()
        {
            WriteLiteral("sssss");


        }
    }
}
